# Generated by Django 3.2.4 on 2021-06-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0002_alter_uploadmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='image',
        ),
    ]
