# Generated by Django 3.2.4 on 2021-06-18 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0003_remove_uploadmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='images'),
            preserve_default=False,
        ),
    ]
