# Generated by Django 3.2.4 on 2021-06-18 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0004_uploadmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='aimodels',
            field=models.CharField(choices=[('Dermatology', 'skin'), ('Cardiology', 'ecg'), ('Radiology', 'xray'), ('COVID', 'ctscan')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
